import streamlit as st
import pandas as pd
import numpy as np

col1, col2, col3 = st.columns([3, 1, 3])
with col2:
    st.image("images/unsplash.svg", width=100)

st.markdown(
    """
    <div style="text-align: center; margin-top: -1.5em;">
        <h2>Alzheimer's Risk Assessment Tool</h2>
        <hr style="border:1px solid #DDD; margin: 1em 0; margin-bottom: 4em;">
        <p style="font-size: 1.2em;">
            This tool supports healthcare professionals in assessing a patient’s risk of developing Alzheimer’s disease based on clinical and test data. Using advanced machine learning methods, it provides data-driven insights to support early intervention and informed decision-making.
        </p>
    </div>
    """,
    unsafe_allow_html=True,
)

# Adding some space between the explanation text and the button
st.markdown("<div style='margin-bottom: 2em;'></div>", unsafe_allow_html=True)

# "Make a prediction" button
col1, col2, col3 = st.columns([3, 2, 3])
with col2:
    if st.button("**Start making a prediction**", key="prediction_btn", use_container_width=True):
        st.switch_page("prediction.py")

st.markdown("---")

# Disclaimer container
with st.container():
    st.markdown(
        """
        <div style="
            border: 1px solid #ECEBE4;
            border-radius: 8px;
            padding: 1em;
            margin-top: 1em;
            background-color: #ECEBE4;
        ">
            <strong>Disclaimer:</strong> This tool is intended to support, not replace, clinical judgment. The risk predictions are generated by machine learning models trained on previously collected clinical and test data. These predictions are not a diagnosis and should always be interpreted by qualified healthcare professionals in the context of each patient’s full medical profile. This tool is for informational and educational purposes only.
        </div>
        """,
        unsafe_allow_html=True,
    )


