import streamlit as st
import pandas as pd
import numpy as np
from fileloader import find_file

col1, col2, col3 = st.columns([3, 3, 3])
with col2:
    st.image(find_file("images/remedi.png"))

with st.container():
    st.markdown(
        """
        <div style="
            border: 1px solid #ECEBE4;
            border-radius: 8px;
            padding: 2em 1em 1.5em 1em;
            margin-top: -1em;
            background-color: #ECEBE4;
            text-align: center;
        ">
            <h2 style="margin-top: -0.1em;">An Alzheimer's Risk Assessment Tool</h2>
            <p style="font-size: 1.1em;">
                This tool aims to support healthcare professionals in assessing a patient’s risk of developing Alzheimer’s disease based on clinical test data. Using advanced machine learning methods, it provides data-driven insights to support early intervention and informed decision-making.
            </p>
        </div>
        """,
        unsafe_allow_html=True,
    )

    # Adding space between the explanation text and the button
    st.markdown("<div style='margin-bottom: 3em;'></div>", unsafe_allow_html=True)

    # "Make a prediction" button
    col1, col2, col3 = st.columns([3, 3, 3])
    with col2:
        if st.button("**Start making a prediction**",type="primary", key="prediction_btn", use_container_width=True):
            st.switch_page("prediction.py")

st.markdown("---")

with st.container():
    st.markdown(
        """
        <div style="font-size: 0.9em; margin-top: -1em;">
            <strong>Disclaimer:</strong> This tool is intended to support, not replace, clinical judgment. The risk predictions are generated by machine learning models trained on previously collected clinical and test data. These predictions are not a diagnosis and should always be interpreted by qualified healthcare professionals in the context of each patient’s full medical profile. This tool is for informational and educational purposes only.
        </div>
        """,
        unsafe_allow_html=True,
    )


